[install]
# Only install package versions published at least 3 days ago
minimumReleaseAge = 259200 # 3 days in seconds
# Our own packages: releases are trusted immediately
minimumReleaseAgeExcludes = ["@cffnpwr/tsconfig", "@cffnpwr/eslint-config"]

[test]
pathIgnorePatterns = "**/dist/**"
