name: commitlint
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  commitlint:
    name: Run commitlint
    uses: cffnpwr/actions/.github/workflows/commitlint.yaml@4e9f696a5b275a6a41747f6d35aa3fad15b9a98a # main
    permissions:
      contents: read
      actions: read
