name: commitlint
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  commitlint:
    name: Run commitlint
    uses: cffnpwr/actions/.github/workflows/commitlint.yaml@00248f03ac888d1695a47b9d4d24738d69c505b8 # main
    permissions:
      contents: read
      actions: read
