name: GitHub Actions Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/*"

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    uses: cffnpwr/actions/.github/workflows/github-actions-lint.yaml@50d431bd4482bb2c49a6b999278b8589d9827dd0 # main
    permissions:
      contents: read
