name: GitHub Actions Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/*"

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    uses: cffnpwr/actions/.github/workflows/github-actions-lint.yaml@558d641533160b48eefd3a635ee1b79530a01227 # main
    permissions:
      contents: read
