name: GitHub Actions Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/*"

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    uses: cffnpwr/actions/.github/workflows/github-actions-lint.yaml@1dfb9f2df96bb6cd5aade81e504399a89bfdf168 # main
    permissions:
      contents: read
