name: Semantic PR title
on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  semantic-pr-title:
    uses: cffnpwr/actions/.github/workflows/semantic-pr-title.yaml@28b9fc713f2f1f49bd979b6c6c6922b1b0c8d48b # main
    permissions:
      pull-requests: read
