name: Status check
on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - edited

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  status-check:
    uses: cffnpwr/actions/.github/workflows/status-check.yaml@10384ba55626671f35459bc0ae86d72ff99951b4 # main
    permissions:
      contents: read
      actions: read
      pull-requests: read
      checks: read
      statuses: read
